### ISSUE TITLE
Scollbars not appearing on colorbox gallery modal

### ISSUE THREAD

**Issue by terah** [JustCarmen/justblack#14] opened 2015-05-23 05:27 UTC
Hi,

Browser: Mac chrome latest and safari latest
OS: OSX Yosemite

Scrollbars are not appearing on the image gallery colorbox modal.

Visit http://sarahcullen.net/individual.php?pid=I00107&ged=GoodCopy.ged and click on the image with the caption 'Parish Map of Yarrunga'.

Terry

**Comment by JustCarmen** [comment] 2015-05-25 06:59
I answered this question earlier at the webtrees issue tracker, and I just put it here for remembrance:

>I took a quick look and the scrollbar just works fine in both safari and chrome. But I've looked from a windows pc. So I think this is not a browser issue but it is the combination with Mac. And that's a problem because I can't test it since I don't have a mac.

In the meantime I've searched the web to find similar issues, but I haven't found any in relation to colorbox. What I do have found are issues with scrollbars when using a Mac. I don't know if it will solve your issue but I think you should give it a try: http://kb.tableau.com/articles/knowledgebase/displaying-scroll-bar

**Comment by terah** [comment] 2015-05-25 07:07
Hi,

They weren't appearing on one mac laptop via chrome but were showing up on another similar mac laptop also in chrome.  I updated chrome on both the laptops and the scrollbars are not showing in either laptops.  They don't appear using Safari either.  It's probably an upstream issue with colorbox and webkit based browsers on Mac.

**Comment by JustCarmen** [comment] 2015-07-12 11:42
Sorry I will close this issue because it is something I can't fix. It is either in the external colorbox code or a bug in the safari/chrome /MAC combination. As far as I can see the problem isn't related to the theme code itself.

**Closed by JustCarmen** 2015-07-12 11:42 UTC
